// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCeADNvulcsSwSh5ZPva6rSAiSzgmHC3Y',
    appId: '1:723587547036:web:3a95f07bd5a0d7b6855259',
    messagingSenderId: '723587547036',
    projectId: 'video-call-app-f6a04',
    authDomain: 'video-call-app-f6a04.firebaseapp.com',
    storageBucket: 'video-call-app-f6a04.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtjQTPlqGzK2EAQ_OxHhJHTNLBtpikXXU',
    appId: '1:723587547036:android:1c707fba3c6dc9d3855259',
    messagingSenderId: '723587547036',
    projectId: 'video-call-app-f6a04',
    storageBucket: 'video-call-app-f6a04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDShipmemNaueoFhWx1w-whtbdRj1xN0t4',
    appId: '1:723587547036:ios:3931c893778019c6855259',
    messagingSenderId: '723587547036',
    projectId: 'video-call-app-f6a04',
    storageBucket: 'video-call-app-f6a04.appspot.com',
    iosBundleId: 'com.example.videoCallApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDShipmemNaueoFhWx1w-whtbdRj1xN0t4',
    appId: '1:723587547036:ios:3931c893778019c6855259',
    messagingSenderId: '723587547036',
    projectId: 'video-call-app-f6a04',
    storageBucket: 'video-call-app-f6a04.appspot.com',
    iosBundleId: 'com.example.videoCallApp',
  );
}
